// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxLO-LfkNX2Vl24nXjWCXVlW24mi9IlXw',
    appId: '1:453628354659:web:28865bc8d4c64221bb1856',
    messagingSenderId: '453628354659',
    projectId: 'wall-c099f',
    authDomain: 'wall-c099f.firebaseapp.com',
    storageBucket: 'wall-c099f.firebasestorage.app',
    measurementId: 'G-NYCEFB27KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEHMwJuKihRgvAnvc4wD0NOV49LaDsO3g',
    appId: '1:453628354659:android:853662b43b79ddf9bb1856',
    messagingSenderId: '453628354659',
    projectId: 'wall-c099f',
    storageBucket: 'wall-c099f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvZe7XZD_qy3uDOSQYvrjmfcG2jDDEflI',
    appId: '1:453628354659:ios:ef68c93a6cc1e6c7bb1856',
    messagingSenderId: '453628354659',
    projectId: 'wall-c099f',
    storageBucket: 'wall-c099f.firebasestorage.app',
    iosBundleId: 'com.example.ig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvZe7XZD_qy3uDOSQYvrjmfcG2jDDEflI',
    appId: '1:453628354659:ios:ef68c93a6cc1e6c7bb1856',
    messagingSenderId: '453628354659',
    projectId: 'wall-c099f',
    storageBucket: 'wall-c099f.firebasestorage.app',
    iosBundleId: 'com.example.ig',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxLO-LfkNX2Vl24nXjWCXVlW24mi9IlXw',
    appId: '1:453628354659:web:ecd7b5e6c939abefbb1856',
    messagingSenderId: '453628354659',
    projectId: 'wall-c099f',
    authDomain: 'wall-c099f.firebaseapp.com',
    storageBucket: 'wall-c099f.firebasestorage.app',
    measurementId: 'G-T5Z0STFKXD',
  );
}
